# Use the official MongoDB image from Docker Hub
FROM mongo:latest

# Set the MongoDB environment variables for automatic configuration
ENV MONGO_INITDB_ROOT_USERNAME=admin
ENV MONGO_INITDB_ROOT_PASSWORD=password

# Expose port 27017 to connect to MongoDB from outside the Docker container
EXPOSE 27017
